import { chmodSync, mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { settingsDir } from './hooksSettings'

const execFileAsync = promisify(execFile)

/**
 * There shouldn't be two kinds of pane. A `claude` you type into a plain shell
 * ought to be monitored exactly like one Torc launched — but hooks arrive via
 * `--settings`, and there's no environment variable for that.
 *
 * So panes get a tiny `claude` shim first on their PATH which injects the flag
 * and execs the real binary. Discovery (poller + process ancestry) already
 * handles identity, so the shim deliberately does *not* touch --session-id:
 * that would collide with `--resume` and `--continue`.
 */
export async function writeClaudeShim(settingsPath: string): Promise<string | undefined> {
  const binDir = join(settingsDir(), 'bin')

  let realClaude: string
  try {
    // Resolve now and hardcode it, so the shim can never exec itself.
    const { stdout } = await execFileAsync('/usr/bin/which', ['claude'], {
      env: await (await import('../env')).resolveUserEnv(),
      encoding: 'utf8',
    })
    realClaude = stdout.trim()
  } catch {
    return undefined
  }
  if (realClaude.length === 0 || realClaude.startsWith(binDir)) return undefined

  const script = `#!/bin/sh
# Generated by Torc — do not edit. Rewritten on every launch.
# Adds Torc's hook settings so a hand-launched \`claude\` reports to the fleet
# view like any other agent. If you pass your own --settings, we stay out of it.
for arg in "$@"; do
  case "$arg" in
    --settings|--settings=*) exec ${JSON.stringify(realClaude)} "$@" ;;
  esac
done
exec ${JSON.stringify(realClaude)} --settings ${JSON.stringify(settingsPath)} "$@"
`

  try {
    mkdirSync(binDir, { recursive: true })
    const shim = join(binDir, 'claude')
    writeFileSync(shim, script)
    chmodSync(shim, 0o755)
    return binDir
  } catch {
    return undefined
  }
}
